### PR TITLE
New Work: Dataset Merging

### LINKED ISSUE #1: New Work : Dataset Merging
## Download The dataset 

**Look for training dataset folder named 'train'. As you can see it is splitted into several datasets try to converge into one training dataset. Here is the picture based description :**
 
image

**so this is the first dataset .Lets check what is has.**

image
**Now lets have a look at second data set and see what it has**.
 
image
image

**Great as you can see all the datasets are having the same type of data and same type of columns. But wait there is a Problem let me show you what it is .**

image

**See this data is from first dataset ; Now lets see same type of data from another Dataset.**

image
 
**Now I hope You got it why this issue has been raised . This is why we have to merge time framed data from several other dataset into one and combine it.**

## Now lets come to PR submission in order to successfully merge it 

1. Download the dataset 
2. Merge it . Please remember that all of the instances has to be covered in total there should be 71225 rows in your Final Dataset.
3. While submitting you have to give a title and a detailed description of your method as well by using appropriate screen shots. Title's starting should be the same  as that of the issue for example I have give this as **NEW WORK**, so your PR should have This title "New Work : Dataset Merging" something like that.
4. After that there is a check list it looks like this Empty Check list --> -[ ] and Filled check list --> -[ X ]. So while Submitting  fill the check list with word "X" between the square brackets.
5. Please link your branch with this issue so that it will automatically closed when it will be merged successfully.
6. PR's will be merged only if all the 71225 rows are present into your dataset.
7. Please assign me as a reviewer for the review of your work and also while submission the PRs label should be as same as that of the issue.
## Checklist 

- [X] Successfully merged the dataset.
- [X] Assigned me as your reviewer.
- [X] This branch has been linked to this issue.
- [X] All the labels of My PR are same as that of the issue.

## Note 
**You can search various methods online for merging the dataset. One Hint I can give you is try using python for this issue's solution. Please do follow the check list in order to successfully merging the PR.**

### PR DESCRIPTION
**Pull request by us107**
**Objective:**
This pull request implements a method to merge multiple CSV files from specified directories while limiting the final DataFrame to 71,225 rows for optimal memory usage.

**Implementation:**
1. Directory Traversal: Used `os.listdir()` to iterate through files in a specified directory.
2. CSV Filtering: Filtered files to process only those ending with `.csv.`
3. DataFrame Initialization: Initialized an empty DataFrame (final_merged_df) for merging.
4.  Concatenation:
      -Used `pandas.concat()` to efficiently combine DataFrames from CSV files.
      -Initially merged the `test` and `train` datasets separately.
5. Final Merging: Combined both the test and train merged` .csv` files into a single `final_merged_file.csv`.
 Screenshot 2024-10-16 235802

7. Row Limitation: Applied `head(71225)` to restrict the DataFrame to 71,225 rows for optimal memory usage.
 Screenshot 2024-10-16 234821

8. Output: Saved the final DataFrame to final_merged_file.csv.

### Checklist
- [X] Successfully merged the dataset.
- [X] Assigned me as your reviewer.
- [X] This branch has been linked to this issue.
- [X] All the labels of my PR are the same as that of the issue.

### CODE REVIEW

**Review by eeshan15 — CHANGES_REQUESTED** [review]
## Review
All Files have been checked. Good work showcased in this PR. I would Like you to kindly go through the checklists under check Lists section of the issue and generate the checklist.

**Comment by us107** [comment]
> ## Review
> All Files have been checked. Good work showcased in this PR. I would Like you to kindly go through the checklists under check Lists section of the issue and generate the checklist.

**Comment by us107** [comment]
checklist done

**Review by eeshan15 — COMMENTED** [review]
Pr has been merged succesfully

**Pull request merged**
